//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPA5BlackBoxReader {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SPA5BlackBoxReader.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reserve.
        /// </summary>
        internal static string alert1 {
            get {
                return ResourceManager.GetString("alert1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no battery charging of channel A.
        /// </summary>
        internal static string alert2 {
            get {
                return ResourceManager.GetString("alert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no battery charging of channel B.
        /// </summary>
        internal static string alert3 {
            get {
                return ResourceManager.GetString("alert3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no battery charging of channel C.
        /// </summary>
        internal static string alert4 {
            get {
                return ResourceManager.GetString("alert4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no battery charging of channel D.
        /// </summary>
        internal static string alert5 {
            get {
                return ResourceManager.GetString("alert5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm active.
        /// </summary>
        internal static string alertActive {
            get {
                return ResourceManager.GetString("alertActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert category not recognized.
        /// </summary>
        internal static string alertCategoryNotRecognized {
            get {
                return ResourceManager.GetString("alertCategoryNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First category.
        /// </summary>
        internal static string alertFirstCategory {
            get {
                return ResourceManager.GetString("alertFirstCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm not active.
        /// </summary>
        internal static string alertNotActive {
            get {
                return ResourceManager.GetString("alertNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert not recognized.
        /// </summary>
        internal static string alertNotRecognized {
            get {
                return ResourceManager.GetString("alertNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second category.
        /// </summary>
        internal static string alertSecondCategory {
            get {
                return ResourceManager.GetString("alertSecondCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System works in automatic mode.
        /// </summary>
        internal static string event10 {
            get {
                return ResourceManager.GetString("event10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical failure of the system.
        /// </summary>
        internal static string event11 {
            get {
                return ResourceManager.GetString("event11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minor failure of the system.
        /// </summary>
        internal static string event12 {
            get {
                return ResourceManager.GetString("event12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train detectors in track 1 are switched on.
        /// </summary>
        internal static string event16 {
            get {
                return ResourceManager.GetString("event16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train detectors in track 2 are switched on.
        /// </summary>
        internal static string event17 {
            get {
                return ResourceManager.GetString("event17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train detectors in track 3 are switched on.
        /// </summary>
        internal static string event18 {
            get {
                return ResourceManager.GetString("event18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to train detectors in track 4 are switched on.
        /// </summary>
        internal static string event19 {
            get {
                return ResourceManager.GetString("event19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general engagement.
        /// </summary>
        internal static string event32 {
            get {
                return ResourceManager.GetString("event32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manual engagement.
        /// </summary>
        internal static string event33 {
            get {
                return ResourceManager.GetString("event33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to control device engagement.
        /// </summary>
        internal static string event34 {
            get {
                return ResourceManager.GetString("event34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retained engagement.
        /// </summary>
        internal static string event35 {
            get {
                return ResourceManager.GetString("event35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to real time clock updated.
        /// </summary>
        internal static string event49 {
            get {
                return ResourceManager.GetString("event49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event active.
        /// </summary>
        internal static string eventActive {
            get {
                return ResourceManager.GetString("eventActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event category not recognized.
        /// </summary>
        internal static string eventCategoryNotRecognized {
            get {
                return ResourceManager.GetString("eventCategoryNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First category.
        /// </summary>
        internal static string eventFirstCategory {
            get {
                return ResourceManager.GetString("eventFirstCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not active.
        /// </summary>
        internal static string eventNotActive {
            get {
                return ResourceManager.GetString("eventNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event not recognized.
        /// </summary>
        internal static string eventNotRecognized {
            get {
                return ResourceManager.GetString("eventNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second category.
        /// </summary>
        internal static string eventSecondCategory {
            get {
                return ResourceManager.GetString("eventSecondCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program info.
        /// </summary>
        internal static string labelAboutProg {
            get {
                return ResourceManager.GetString("labelAboutProg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary file.
        /// </summary>
        internal static string labelBin {
            get {
                return ResourceManager.GetString("labelBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string labelCategory {
            get {
                return ResourceManager.GetString("labelCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel.
        /// </summary>
        internal static string labelChannel {
            get {
                return ResourceManager.GetString("labelChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string labelChngLang {
            get {
                return ResourceManager.GetString("labelChngLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string labelClose {
            get {
                return ResourceManager.GetString("labelClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded alarms and events.
        /// </summary>
        internal static string labelDecEvent {
            get {
                return ResourceManager.GetString("labelDecEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoded alarms and events.
        /// </summary>
        internal static string labelDecEventTable {
            get {
                return ResourceManager.GetString("labelDecEventTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string labelFile {
            get {
                return ResourceManager.GetString("labelFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string labelGroup {
            get {
                return ResourceManager.GetString("labelGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string labelInfo {
            get {
                return ResourceManager.GetString("labelInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LX Number.
        /// </summary>
        internal static string labelLxNumber {
            get {
                return ResourceManager.GetString("labelLxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm/Event name.
        /// </summary>
        internal static string labelName {
            get {
                return ResourceManager.GetString("labelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string labelNumber {
            get {
                return ResourceManager.GetString("labelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string labelRead {
            get {
                return ResourceManager.GetString("labelRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string labelStatus {
            get {
                return ResourceManager.GetString("labelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string labelStop {
            get {
                return ResourceManager.GetString("labelStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string labelTime {
            get {
                return ResourceManager.GetString("labelTime", resourceCulture);
            }
        }
    }
}
